version: "3.9"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./images:/app/images
    # TODO: THIS IS FOR TESTING ONLY - Remove before deploying
    ports:
      - 3000:3000
    depends_on:
      - db